### ISSUE TITLE
Doesn't seem to work on F40

### ISSUE THREAD

**Issue by Nasdrovia69** [thevladsoft/change-file-date-time#2]
Hello
on F40 it doesn't seem to work anymore, maybe it's time to revise the code, as I love your app.
Thanks

**Comment by thevladsoft** [comment]
Plasma 6 changed the folders of servicemenus. So, for plasma 6, if using the "Download new services" dialog, select the .desktop file directly. If that fails (early versions of plasma 6 seems to fail), download de .desktop file and copy in $HOME/.local/share/kio/servicemenus/
